common: Explicitly depend on gio-unix-2.0
This fixes the following on NixOS:

xfce-notify-log-util.c:40:10: fatal error: gio/gdesktopappinfo.h: No such file or directory
   40 | #include <gio/gdesktopappinfo.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

The reason here is the same as https://gitlab.xfce.org/xfce/xfce4-session/-/merge_requests/51.