Fix missing-prototypes
xfce-notify-log.c:406:6: error: no previous prototype for 'xfce_notify_clear_icon_cache' [-Werror=missing-prototypes]

Signed-off-by: Olaf Hering <olaf@aepfle.de>